Repository Ruhinda01/AirBnB_clone_v3, pull requests merged in 2024-04, with the labels that each got.

#1 Storage get count
  models/engine/db_storage.py
  models/engine/file_storage.py
Labels: enhancement

#2 Start on API creation
  api/__init__.py
  api/v1/__init__.py
  api/v1/app.py
  api/v1/views/__init__.py
  api/v1/views/index.py
Labels: enhancement

#3 Tests
  test_get_count.py
  tests/test_models/test_engine/test_db_storage.py
  tests/test_models/test_engine/test_file_storage.py
Labels: help wanted

#4 New route
  api/v1/views/index.py
Labels: enhancement

#5 Add error handler
  api/v1/app.py
Labels: enhancement

#6 Api number 6
  api/v1/views/__init__.py
  api/v1/views/states.py
Labels: enhancement

#7 Amenity
  api/v1/views/amenities.py
Labels: enhancement

#8 Create a cities view
  api/v1/views/__init__.py
  api/v1/views/cities.py
Labels: enhancement

#9 Make the changes to Check as discussed
  api/v1/views/amenities.py
  api/v1/views/cities.py
  api/v1/views/states.py
Labels: bug

#11 Create a places view
  api/v1/views/__init__.py
  api/v1/views/places.py
Labels: enhancement

#12 number 11
  api/v1/views/places_reviews.py
Labels: enhancement

#13 Add CORS functionality
  api/v1/app.py
Labels: enhancement
